name: "Decode Secrets"
description: "Decode keystores and google-services.json"
runs:
  using: "composite"
  steps:
    - run: |
        echo "${{ secrets.RELEASE_KEY_BASE_64 }}" | base64 -d > release.jks
        mkdir -p app/keystore/debug
        echo "${{ secrets.DEBUG_KEY_BASE_64 }}" | base64 -d > app/keystore/debug/debug.jks
        echo "${{ secrets.DEBUG_KEY_PROPERTIES }}" | base64 -d > app/keystore/debug/debug.properties
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json
      shell: bash
