name: Open SMS Forwarder CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
  RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  FEEDBACK_DB_PATH: ${{ secrets.FEEDBACK_DB_PATH }}

defaults:
  run:
    shell: bash

jobs:

  prepare:
    name: Setup & Decode Keys
    runs-on: ubuntu-latest
    outputs:
      gradle-cache-key: ${{ steps.gradle-cache.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Cache Gradle
        id: gradle-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

#      - name: Decode Keystores and google-services.json
#        run: |
#          mkdir -p app/keystore/debug
#          echo "${{ secrets.RELEASE_KEY_BASE_64 }}" | base64 -di > release.jks
#          echo "${{ secrets.DEBUG_KEY_BASE_64 }}" | base64 -di > app/keystore/debug/debug.jks
#          echo "${{ secrets.DEBUG_KEY_PROPERTIES }}" | base64 -di > app/keystore/debug/debug.properties
#          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -di > app/google-services.json

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew detekt --build-cache --parallel

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: Decode Keystore
        run: |
          mkdir -p app/keystore/debug
          echo "${{ secrets.DEBUG_KEY_BASE_64 }}" | base64 -d > app/keystore/debug/debug.jks
          echo "${{ secrets.DEBUG_KEY_PROPERTIES }}" | base64 -d > app/keystore/debug/debug.properties

      - name: Decode google-services.json
        run: mkdir -p app && echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - run: ./gradlew testDebugUnitTest --build-cache --parallel

  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          mkdir -p app/keystore/debug
          echo "${{ secrets.DEBUG_KEY_BASE_64 }}" | base64 -d > app/keystore/debug/debug.jks
          echo "${{ secrets.DEBUG_KEY_PROPERTIES }}" | base64 -d > app/keystore/debug/debug.properties

      - name: Decode google-services.json
        run: mkdir -p app && echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: "-no-window -no-audio -gpu swiftshader_indirect"
          disable-animations: true
          script: ./gradlew connectedCheck --build-cache --parallel

  build-release:
    name: Build APK & AAB
    runs-on: ubuntu-latest
    needs: [static-analysis, unit-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEY_BASE_64 }}" | base64 -d > release.jks
          mkdir -p app/keystore/debug
          echo "${{ secrets.DEBUG_KEY_BASE_64 }}" | base64 -d > app/keystore/debug/debug.jks
          echo "${{ secrets.DEBUG_KEY_PROPERTIES }}" | base64 -d > app/keystore/debug/debug.properties

      - name: Decode google-services.json
        run: mkdir -p app && echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Make schema check executable
        run: chmod +x scripts/check_room_schema_drift.sh

      - name: Run Room schema drift check
        run: ./scripts/check_room_schema_drift.sh
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_BASE_REF: ${{ github.base_ref }}

      - name: Build Release APK and AAB
        run: ./gradlew assembleRelease bundleRelease --build-cache --parallel

      - name: Get release apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Get release aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_OUTPUT

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-artifacts
          path: ${{ steps.releaseApk.outputs.apkfile }}

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-artifacts
          path: ${{ steps.releaseAab.outputs.aabfile }}
