name: Bump Version and Tag

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git (GitHub Actions bot)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Read and bump version
        id: bump
        run: |
          VERSION=$(grep VERSION_NAME version.properties | cut -d= -f2)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          NEW_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))

          echo "New version: $NEW_VERSION ($NEW_CODE)"
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "new_code=$NEW_CODE" >> "$GITHUB_OUTPUT"

          echo "VERSION_NAME=$NEW_VERSION" > version.properties
          echo "VERSION_CODE=$NEW_CODE" >> version.properties

      - name: Commit version bump
        run: |
          git add version.properties
          git commit -m "ci: bump version to ${{ steps.bump.outputs.new_version }}"
          git push

      - name: Create Git Tag
        run: |
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin v${{ steps.bump.outputs.new_version }}
